#!/bin/bash

dir="$HOME/Documents/Notes/$(date '+%Y/%m')"
file="$dir/$(date '+%Y-%m-%d.txt')"

if [[ ! -d "$dir"  ]]; then mkdir -p "$dir"; fi
if [[ ! -f "$file" ]]; then touch "$file"; fi
gedit "$file" &
